### PR TITLE
Segfault grdid

### PR DESCRIPTION
**Pull request by MathieuDutSik**
This PR addresses two problems:
--- Unset variables.
--- different memory size (10 vs 13) in the variable GRDID.

### CODE REVIEW

**Comment by thesser1** [comment]
@MathieuDutSik, when running the regtests, I noticed that beyond just the binary files, a few netcdf output files changed.  Looking at your changes, I am trying to figure out what has caused the differences.  Could you help me understand?  I have attached the comparison files from the regtests.  
[FB_segfault_regtests.zip](https://github.com/erdc/WW3/files/3530593/FB_segfault_regtests.zip)

**Comment by MathieuDutSik** [comment]
Hi Tyler,

Thank you for this information.

I look at the files you sent me and I have following findings/questions:

1) The difference in netcdf files is following:
-----------------------------------
/p/work/thesser1/ww3_eval/WW3/regtests/output/ww3_tp2.15/work_5km/ww3.201403.nc_diff.txt
***
169c169
<               :WAVEWATCH_III_version_number = "6.07" ;
---
>               :WAVEWATCH_III_version_number = "7.00" ;
------------------------------------
So, to me those are insignificant. Just version numbers.



2) Many of the differences happen in the point output:
     out_pnt.ww3 differ (binary)
I well know that there is a bug in the point output in the multigrid
runs. I spent weeks searching for that one without success. I think
this is unrelated to PDLIB and our works. Will continue to work to
crack that bug.



3) Another difference appears is
     gmon.out differ (binary)
and I do not know what this is about.



4) The matrix information is certainly useful.
Q1: How to create it?
Q2: How to get more information? Right now we have
     * test case: mww3_test_01; test run: ./work_PR2_UNO_MPI
which misses for example on how many processors are
available.
Q3: The differ is between what and what? Is it the difference
between "develop" and "segfault_grid"?



Best wishes,

  Mathieu

**Comment by thesser1** [comment]
Great yes. It all makes sense.  
Q1.   The matrix info is in regtests.  There is documentation in the wiki page on the main EMC repo for setting up and running your own matrix
Q2.   I am happy to provide more info on these regtests.  I run with 24 cores which is the same number of cores as EMC uses when running their tests.  However, this is decided by the person setting up the matrix
Q3.  The results I am showing are the differences between develop and segfault_grid merged into the latest version of develop.  

Given your explanations, I will likely approve your pull request and make a pull request to the EMC repo for the rest of the team to approve.  
Thanks,
Ty

**Comment by MathieuDutSik** [comment]
Ok, let me know when the PR is accepted or if there is another problem
that blocks.

  Mathieu

**Comment by thesser1** [comment]
This pull request was merged directly into the NOAA-EMC/WW3 develop branch and then was merged from upstream into erdc/WW3.

**Pull request closed without merging**
